#!/usr/bin/env bash
# configures a new Ubuntu machine to return 
#a page that contains the string Hello World! When querying Nginx at its root /
sudo chmod -R 757 /var/www
echo "Hello World!" > /var/www/html/index.html
