#!/usr/bin/env bash
# Configure Nginx server for /redirect_me to redirect to another page.
apt -y update
apt -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
command="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s/server_name _;/$command/" /etc/nginx/sites-available/default
service nginx start
