#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server
apt update -y
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y install haproxy=2.6.\*
echo "ENABLED=1" >> /etc/default/haproxy
echo -e "\nfrontend http\n\tbind *:80\n\tdefault_backend servers" >> /etc/haproxy/haproxy.cfg
echo -e "\n\nbackend servers\n\tbalance roundrobin\n\tserver 150520-web-01 18.209.224.36:80 check\n\tserver 150520-web-02 52.72.32.178:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
