#!/usr/bin/env bash
echo -e "\nfrontend http\n\tbind *:80\n\tdefault_backend servers" >> fg
echo -e "\n\nbackend servers\n\tbalance roundrobin\n\tserver 150520-web-01 18.209.224.36:80 check\n\tserver 150520-web-02 52.72.32.178:80 check" >> fg
