#!/usr/bin/env bash
#Debug Ubuntu container's Nginx installation
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sed -i "s/listen 8080 default_server;/listen 80 default_server;/" /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:8080 default_server ipv6only=on/listen \[::\]:80 default_server ipv6only=on/' /etc/nginx/sites-enabled/default
service nginx restart
